const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const webpack = require('webpack');

module.exports = {
  mode: 'production',
  target: 'web',
  entry: {
    'index': './src/Isoflow.tsx',
    '/standaloneExports': './src/standaloneExports.ts',
  },
  output: {
    path: path.resolve(__dirname, '../dist'),
    filename: '[name].js',
    libraryTarget: 'commonjs2'
  },
  externals: {
    react: {
      commonjs: 'react',
      commonjs2: 'react',
      amd: 'React',
      root: 'React'
    },
    'react-dom': {
      commonjs: 'react-dom',
      commonjs2: 'react-dom',
      amd: 'ReactDOM',
      root: 'ReactDOM'
    },
    '@mui/material': 'commonjs2 @mui/material',
    '@mui/icons-material': 'commonjs2 @mui/icons-material',
    '@emotion/react': 'commonjs2 @emotion/react',
    '@emotion/styled': 'commonjs2 @emotion/styled',
    zustand: 'commonjs2 zustand',
    immer: 'commonjs2 immer',
    paper: 'commonjs2 paper',
    gsap: 'commonjs2 gsap'
  },
  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        use: {
          loader: 'ts-loader',
          options: {
            // Declarations for the published package are generated by the
            // dedicated `tsc --declaration --emitDeclarationOnly` step that
            // runs right after webpack (see the `build` npm script). Two
            // entry points (`index` and `/standaloneExports`) both pull in
            // shared modules (e.g. via `src/utils`), and letting ts-loader
            // also emit `.d.ts` assets here can make webpack see two
            // different declaration outputs for the same shared module —
            // "Conflict: Multiple assets emit different content to the
            // same filename". Turning declaration emission off here avoids
            // that class of bug entirely; it's redundant work anyway.
            compilerOptions: {
              declaration: false,
              declarationMap: false
            }
          }
        },
        exclude: /node_modules/
      },
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.svg$/,
        type: 'asset/inline'
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      PACKAGE_VERSION: JSON.stringify(require("../package.json").version),
      REPOSITORY_URL: JSON.stringify(require("../package.json").repository.url),
    })
  ],
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
    plugins: [new TsconfigPathsPlugin()]
  }
};
